Added makefile to fifo etc examples

diff --git a/cdc_fifo_arbiters/bin/rr b/cdc_fifo_arbiters/bin/rr
--- a/cdc_fifo_arbiters/bin/rr
+++ b/cdc_fifo_arbiters/bin/rr
@@ -1,10 +1,221 @@
-#!/bin/sh
+#!/bin/bash
 
-rm -rf sim
-mkdir -p sim
-cd sim
+set +e  # Don't exit immediately if a command exits with a non-zero status
 
-iverilog -g2005 ../*.v
-vvp a.out > a.lst
-cat a.lst
-gtkwave dump.vcd -S ../gtkwave.tcl
+#-----------------------------------------------------------------------------
+
+readonly script=$(basename "$0")
+
+#-----------------------------------------------------------------------------
+
+export MODELSIM_ROOTDIR="$HOME/intelFPGA_lite/18.1/modelsim_ase"
+export PATH="${PATH}:$MODELSIM_ROOTDIR/bin"
+export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$MODELSIM_ROOTDIR/lib32"
+
+SIM_DIR=${PWD}/sim
+SYN_DIR=${PWD}/syn
+
+#-----------------------------------------------------------------------------
+
+error ()
+{
+    ec=$1
+    shift
+
+    [ $ec != 0 ] || return
+
+    printf "$script: error: $*" 1>&2
+    
+    if [ $ec != 1 ]
+    then
+        printf ". Exiting with code $ec." 1>&2
+    fi
+    
+    printf "\n" 1>&2
+    exit $ec
+}
+
+#-----------------------------------------------------------------------------
+
+warning ()
+{
+    printf "$script: warning: $*\n" 1>&2
+}
+
+#-----------------------------------------------------------------------------
+
+info ()
+{
+    printf "$script: $*\n" 1>&2
+}
+
+#-----------------------------------------------------------------------------
+
+is_command_available ()
+{
+    command -v $1 &> /dev/null
+}
+
+#-----------------------------------------------------------------------------
+
+is_command_available_or_error ()
+{
+    is_command_available $1 ||  \
+        error 1 "program $1$2 is not in the path or cannot be run"
+}
+
+#-----------------------------------------------------------------------------
+
+guarded ()
+{
+    is_command_available_or_error $1
+    eval "$*" || error $? "cannot $*"
+}
+
+#-----------------------------------------------------------------------------
+
+guarded rm    -rf $SIM_DIR
+guarded mkdir -p  $SIM_DIR
+guarded cd        $SIM_DIR
+
+#-----------------------------------------------------------------------------
+
+run_iverilog=0
+run_gtkwave=0
+run_vsim=0
+
+is_command_available iverilog && run_iverilog=1
+is_command_available gtkwave  && run_gtkwave=1
+is_command_available vsim     && run_vsim=1
+
+#-----------------------------------------------------------------------------
+
+if [ $run_iverilog = 1 ] && [ $run_vsim = 1 ]
+then
+    # Icarus has priority
+    run_vsim=0
+fi
+
+if [ $run_iverilog = 1 ] && [ $run_vsim = 1 ]
+then
+    printf "Two Verilog simulators are available to run:"
+    printf " Icarus Verilog and Mentor ModelSim\n"
+    printf "Which do you want to run?\n"
+
+    options="Icarus ModelSim Both"
+    PS3="Your choice: "
+
+    select simulator in $options
+    do
+        case $simulator in
+        Icarus)   run_vsim=0     ; break ;;
+        ModelSim) run_iverilog=0 ; break ;;
+        Both)                      break ;;
+        esac
+    done
+fi
+
+if [ $run_iverilog = 0 ] && [ $run_gtkwave = 1 ]
+then
+    run_gtkwave=0
+fi
+
+[ $run_iverilog = 0 ] && [ $run_vsim = 0 ] &&  \
+    error 1 "No Verilog simulator is available to run."  \
+            "You need to install either Icarus Verilog"  \
+            "or Mentor Questa / ModelSim."
+
+#-----------------------------------------------------------------------------
+
+if [ $run_iverilog = 1 ]
+then
+    iverilog -g2005 -I .. ../*.v &> icarus.compile.log
+    ec=$?
+
+    if [ $ec != 0 ]
+    then
+        grep -i -A 5 error icarus.compile.log 2>&1
+        error $ec Icarus Verilog compiler errors
+    fi
+
+    vvp a.out &> icarus.simulate.log
+    ec=$?
+
+    sed -i '/^VCD info: dumpfile dump.vcd opened for output.$/d'  \
+        icarus.simulate.log
+
+    if [ $ec != 0 ]
+    then
+        grep -i -A 5 error icarus.simulate.log 2>&1
+        tail -n 5 icarus.simulate.log 2>&1
+        error $ec Icarus Verilog simulator errors
+    fi
+
+    info Icarus Verilog simulation successfull
+    tail -n 5 icarus.simulate.log
+fi
+
+#-----------------------------------------------------------------------------
+
+if [ $run_gtkwave = 1 ]
+then
+    ec=0
+
+    if    [ "$OSTYPE" = "linux-gnu" ]  \
+       || [ "$OSTYPE" = "cygwin"    ]  \
+       || [ "$OSTYPE" = "msys"      ]
+    then
+        gtkwave --dump dump.vcd --script ../gtkwave.tcl &> waveform.log
+
+    elif [ ${OSTYPE/[0-9]*/} = "darwin" ]
+    # elif [[ "$OSTYPE" = "darwin"* ]]  # Alternative way
+    then
+        # For some reason the following way of opening the application
+        # does not read the script file:
+        #
+        # open -a gtkwave dump.vcd --args --script $PWD/../gtkwave.tcl
+        #
+        # This way works:
+
+        /Applications/gtkwave.app/Contents/MacOS/gtkwave-bin  \
+            --dump dump.vcd --script ../gtkwave.tcl &> waveform.log
+    else
+        error 1 "don't know how to run GTKWave on your OS $OSTYPE"
+    fi
+
+    ec=$?
+
+    if [ $ec != 0 ]
+    then
+        grep -i -A 5 error waveform.log 2>&1
+        error $ec "waveform viewer failed"
+    fi
+fi
+
+#-----------------------------------------------------------------------------
+
+if [ $run_vsim = 1 ]
+then
+    ec=0
+
+    if    [ "$OSTYPE" = "linux-gnu" ]  \
+       || [ "$OSTYPE" = "cygwin"    ]  \
+       || [ "$OSTYPE" = "msys"      ]
+    then
+        vsim -do ../modelsim.tcl &> modelsim.log
+    else
+        error 1 "don't know how to run ModelSim on your OS $OSTYPE"
+    fi
+
+    ec=$?
+
+    if [ $ec != 0 ]
+    then
+        grep -i -A 5 error modelsim.log 2>&1
+        error $ec "ModelSim failed"
+    fi
+fi
+
+#-----------------------------------------------------------------------------
+
+exit 0
